stsproject/goodsapp/urls.py
from django.urls import path
from .views import index, order_review, search_product, upload_order, confirm_delete_order, upload_order_view, \
    delete_product

app_name = 'goodsapp'
# пространство имен включается в тег url в шаблоне

urlpatterns = [
    path('', index, name='index'),
    path('order_review/<int:order_id>/', order_review, name='order_review'),
    path('orders/<int:order_id>/search', search_product, name='search_product'),
    path('upload/', upload_order_view, name='upload_order'),
    path('order/<int:order_id>/confirm-delete/', confirm_delete_order, name='confirm_delete_order'),
    path('product/delete/<int:product_id>/', delete_product, name='delete_product'),
]

stsproject/stsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include("debug_toolbar.urls")),
    path('users/', include('usersapp.urls')),
    path('',include('goodsapp.urls'))

]
#
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stsproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}Base title{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<!-- Сообщения -->
{% if messages %}
<div class="alert alert-success" role="alert">
    {% for message in messages %}
        {{ message }}
    {% endfor %}
</div>
{% endif %}

{% include 'navbar.html' %}
<div class="container">
  {% block content %}

  Content

  {% endblock %}

    </div>

<footer class="text-center">
   <div class="social-links">
       <a href="https://github.com/Andreysx">Git</a>
   </div>
    <div class="contact-info">
        <p>Email: drontop1999@mail.ru</p>
    </div>
    <p>&copy; Fun </p>
    </footer>

<script>
document.querySelectorAll('.accordion-button').forEach(button => {
    button.addEventListener('click', () => {
        const content = button.nextElementSibling;

        // Переключение класса open для анимации
        content.classList.toggle('open');

        // Переключение видимости контента
        if (content.classList.contains('open')) {
            content.style.maxHeight = content.scrollHeight + "px"; // Устанавливаем высоту для анимации
        } else {
            content.style.maxHeight = null; // Сбрасываем высоту
        }
    });
});
</script>
</body>
</html>

stsproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'goodsapp:index' %}">Справочник артикулов</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page"
                       href="{% url 'goodsapp:index' %}">
                            Заказы
                    </a>
                </li>
            </ul>
             <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == 'upload/' %}active{% endif %}" aria-current="page"
                       href="{% url 'goodsapp:upload_order' %}">
                            Загрузить файл
                    </a>
                </li>
            </ul>
             <ul class="navbar-nav mb-2 mb-lg-0">
                 {% if user.is_authenticated %}
                <li class="nav-item">
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button class="nav-link" type="submit">Выйти</button>
                    </form>
                </li>
                {% else %}
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.path_info == '/users/register/' %}active{% endif %}"
                       href="{% url 'register' %}">
                        Регистрация
                        </a>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path_info == '/users/login/' %}active{% endif %}"
                        href="{% url 'login' %}">
                        Авторизация
                    </a>
                </li>
                 {% endif %}
            </ul>
        </div>
    </div>
</nav>